---
- name: Attempting to generate temporary file
  tags: remi
  tempfile:
    prefix: 'remi.'
    state: file
    suffix: '.rpm'
  register: remi_tempfile

- name: Attempting to download package to temporary location
  tags: remi
  get_url:
    dest: "{{ remi_tempfile.path }}"
    force: yes
    url: "{{ remi_fetch }}"
  register: remi_get_url
  when: remi_tempfile is success

- name: Ensure that the {{ remi_pkg }} package is installed
  tags: remi
  become: true
  yum:
    disable_plugin: "{{ remi_disable_plugin|join(',') }}"
    disablerepo: "{{ remi_disablerepo|join(',') }}"
    enable_plugin: "{{ remi_enable_plugin|join(',') }}"
    enablerepo: "{{ remi_enablerepo|join(',') }}"
    name: "{{ remi_tempfile.path }}"
    state: present
  register: remi_yum
  when: remi_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: remi
  file:
    path: "{{ remi_tempfile.path }}"
    state: absent
  when:
    - remi_tempfile is success
    - remi_yum is success

- name: Attempting to overlay remi repository configurations
  tags: remi
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: remi.repo.j2, dst: /etc/yum.repos.d/remi.repo }
    - { src: remi-glpi91.repo.j2, dst: /etc/yum.repos.d/remi-glpi91.repo }
    - { src: remi-glpi92.repo.j2, dst: /etc/yum.repos.d/remi-glpi92.repo }
    - { src: remi-glpi93.repo.j2, dst: /etc/yum.repos.d/remi-glpi93.repo }
    - { src: remi-php54.repo.j2, dst: /etc/yum.repos.d/remi-php54.repo }
    - { src: remi-php70.repo.j2, dst: /etc/yum.repos.d/remi-php70.repo }
    - { src: remi-php71.repo.j2, dst: /etc/yum.repos.d/remi-php71.repo }
    - { src: remi-php72.repo.j2, dst: /etc/yum.repos.d/remi-php72.repo }
    - { src: remi-safe.repo.j2, dst: /etc/yum.repos.d/remi-safe.repo }
  loop_control:
    label: "{{ item.src.split('.')[0] }}"
  when: remi_yum is success

- name: Ensure that the remi gpg keys are installed
  tags: remi
  become: true
  rpm_key:
    key: "{{ item }}"
    state: present
  loop:
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-remi2017
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-remi2018
  loop_control:
    label: "{{ item.split('/')[4] }}"
  when: remi_yum is success

- name: Ensure that the required remi packages are installed
  tags: remi
  become: true
  yum:
    disable_plugin: "{{ remi_disable_plugin|join(',') }}"
    disablerepo: "{{ remi_disablerepo|join(',') }}"
    enable_plugin: "{{ remi_enable_plugin|join(',') }}"
    enablerepo: "{{ remi_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  loop: "{{ remi_packages }}"
  when:
    - remi_packages|length > 0
    - remi_yum is success
...
