---
- name: Assert that the prerequisites are defined
  tags: remi
  assert:
    that:
      - remi_pkg is defined
      - remi_rel is defined
      - remi_baseurl is defined

- name: Generating temporary filename via mktemp
  tags: remi
  command: mktemp -u --suffix .rpm
  register: remi_mktemp

- name: Downloading package to temporary location
  tags: remi
  get_url:
    url: "{{ remi_fetch }}"
    dest: "{{ remi_mktemp.stdout }}"
  register: remi_get_url
  when: remi_mktemp|success

- name: Ensure that the remi-release package is installed
  tags: remi
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: remi_yum
  with_items: "{{ remi_mktemp.stdout }}"
  when: remi_get_url|success

- name: Applying remi repository configurations
  tags: remi
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: remi.repo.j2, dst: /etc/yum.repos.d/remi.repo }
    - { src: remi-php54.repo.j2, dst: /etc/yum.repos.d/remi-php54.repo }
    - { src: remi-php70.repo.j2, dst: /etc/yum.repos.d/remi-php70.repo }
    - { src: remi-php71.repo.j2, dst: /etc/yum.repos.d/remi-php71.repo }
    - { src: remi-php72.repo.j2, dst: /etc/yum.repos.d/remi-php72.repo }
    - { src: remi-safe.repo.j2, dst: /etc/yum.repos.d/remi-safe.repo }
  when: remi_yum|success

- name: Ensure that the Remi GPG keys are installed
  tags: remi
  become: true
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
    - /etc/pki/rpm-gpg/RPM-GPG-KEY-remi2017

- name: Purging temporary package from filesystem
  tags: remi
  file:
    path: "{{ remi_mktemp.stdout }}"
    state: absent
  when:
    - remi_mktemp|success
    - remi_yum|success
...
