---
- name: Assert that prerequisites exist
  tags: remi
  assert:
    that:
      - remi_pkg is defined
      - remi_rel is defined
      - remi_baseurl is defined

- name: Generate random package name
  tags: remi
  command: mktemp -u --suffix .rpm
  register: remi_mktemp

- name: Fetch {{ remi_pkg }} to temporary destination
  tags: remi
  get_url:
    url: "{{ remi_fetch }}"
    dest: "{{ remi_mktemp.stdout }}"
  register: remi_get_url
  when: remi_mktemp|success

- name: Ensure that the {{ remi_pkg }} package is installed
  tags: remi
  yum:
    name: "{{ item }}"
    state: present
  register: remi_yum
  with_items: "{{ remi_mktemp.stdout }}"
  when: remi_get_url|success

- name: Applying {{ remi_pkg }} configurations
  tags: remi
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: remi.repo.j2, dst: /etc/yum.repos.d/remi.repo }
    - { src: remi-php70.repo.j2, dst: /etc/yum.repos.d/remi-php70.repo }
    - { src: remi-safe.repo.j2, dst: /etc/yum.repos.d/remi-safe.repo }
  when: remi_yum|success

- name: Prune temporary package from the filesystem
  tags: remi
  file:
    path: "{{ remi_mktemp.stdout }}"
    state: absent
  when:
    - remi_mktemp|success
    - remi_yum|success
...
